import { PrismaClient } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';

const prisma = new PrismaClient();

async function main() {
  // -----------------------------
  // Plans Seed
  // -----------------------------
  await prisma.plan.createMany({
    data: [
      {
        id: 1,
        name: '5G 슈퍼플랜',
        price: 95000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('5.0'),
        voice_minutes: -1,
        sms_included: 200,
        network_type: '5G',
        subscription_services: ['NETFLIX', 'YOUTUBE_PREMIUM'],
        badges: [],
      },
      {
        id: 2,
        name: '5G 스탠다드',
        price: 75000,
        data_amount_mb: 100000,
        overage_speed_mbps: new Decimal('3.0'),
        voice_minutes: 1000,
        sms_included: 100,
        network_type: '5G',
        subscription_services: ['DISNEY+'],
        badges: [],
      },
      {
        id: 3,
        name: 'LTE 베이직',
        price: 45000,
        data_amount_mb: 50000,
        overage_speed_mbps: new Decimal('1.0'),
        voice_minutes: 500,
        sms_included: 50,
        network_type: 'LTE',
        subscription_services: ['WAVVE', 'TVING'],
        badges: [],
      },
      {
        id: 4,
        name: '5G 프리미엄',
        price: 120000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('10.0'),
        voice_minutes: -1,
        sms_included: 300,
        network_type: '5G',
        subscription_services: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+'],
        badges: [],
      },
      {
        id: 5,
        name: 'LTE 라이트',
        price: 35000,
        data_amount_mb: 30000,
        overage_speed_mbps: new Decimal('0.5'),
        voice_minutes: 300,
        sms_included: 30,
        network_type: 'LTE',
        subscription_services: [],
        badges: [],
      },
      {
        id: 6,
        name: '5G 미디엄',
        price: 65000,
        data_amount_mb: 80000,
        overage_speed_mbps: new Decimal('2.0'),
        voice_minutes: 800,
        sms_included: 80,
        network_type: '5G',
        subscription_services: ['MILLIE'],
        badges: [],
      },
      {
        id: 7,
        name: 'LTE 스탠다드',
        price: 55000,
        data_amount_mb: 60000,
        overage_speed_mbps: new Decimal('1.5'),
        voice_minutes: 600,
        sms_included: 60,
        network_type: 'LTE',
        subscription_services: ['TVING'],
        badges: [],
      },
      {
        id: 8,
        name: '5G 울트라',
        price: 150000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('15.0'),
        voice_minutes: -1,
        sms_included: 500,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'WAVVE',
          'TVING',
        ],
        badges: [],
      },
      {
        id: 9,
        name: '5G 스마트',
        price: 85000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('4.0'),
        voice_minutes: -1,
        sms_included: 150,
        network_type: '5G',
        subscription_services: ['YOUTUBE_PREMIUM', 'WAVVE'],
        badges: ['인기'],
      },
      {
        id: 10,
        name: 'LTE 프리미엄',
        price: 60000,
        data_amount_mb: 70000,
        overage_speed_mbps: new Decimal('1.2'),
        voice_minutes: 700,
        sms_included: 70,
        network_type: 'LTE',
        subscription_services: ['TVING'],
        badges: [],
      },
      {
        id: 11,
        name: '5G 스타터',
        price: 55000,
        data_amount_mb: 40000,
        overage_speed_mbps: new Decimal('1.5'),
        voice_minutes: 400,
        sms_included: 40,
        network_type: '5G',
        subscription_services: [],
        badges: ['신규'],
      },
      {
        id: 12,
        name: 'LTE 플러스',
        price: 50000,
        data_amount_mb: 55000,
        overage_speed_mbps: new Decimal('1.0'),
        voice_minutes: 550,
        sms_included: 55,
        network_type: 'LTE',
        subscription_services: ['WAVVE'],
        badges: [],
      },
      {
        id: 13,
        name: '5G 엔터테인먼트',
        price: 110000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('8.0'),
        voice_minutes: -1,
        sms_included: 400,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'TVING',
        ],
        badges: ['추천'],
      },
      {
        id: 14,
        name: 'LTE 이코노미',
        price: 30000,
        data_amount_mb: 25000,
        overage_speed_mbps: new Decimal('0.3'),
        voice_minutes: 250,
        sms_included: 25,
        network_type: 'LTE',
        subscription_services: [],
        badges: ['저렴'],
      },
      {
        id: 15,
        name: '5G 비즈니스',
        price: 130000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('12.0'),
        voice_minutes: -1,
        sms_included: 600,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'WAVVE',
          'TVING',
          'MILLIE',
        ],
        badges: ['프리미엄'],
      },
      {
        id: 16,
        name: 'LTE 미디엄',
        price: 48000,
        data_amount_mb: 45000,
        overage_speed_mbps: new Decimal('0.8'),
        voice_minutes: 450,
        sms_included: 45,
        network_type: 'LTE',
        subscription_services: [],
        badges: [],
      },
      {
        id: 17,
        name: '5G 게이밍',
        price: 100000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('7.0'),
        voice_minutes: -1,
        sms_included: 350,
        network_type: '5G',
        subscription_services: ['YOUTUBE_PREMIUM'],
        badges: ['특화'],
      },
      {
        id: 18,
        name: 'LTE 스마트',
        price: 42000,
        data_amount_mb: 40000,
        overage_speed_mbps: new Decimal('0.7'),
        voice_minutes: 400,
        sms_included: 40,
        network_type: 'LTE',
        subscription_services: ['WAVVE'],
        badges: [],
      },
      {
        id: 19,
        name: '5G 패밀리',
        price: 140000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('9.0'),
        voice_minutes: -1,
        sms_included: 450,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'WAVVE',
        ],
        badges: ['가족'],
      },
      {
        id: 20,
        name: 'LTE 베이직 플러스',
        price: 38000,
        data_amount_mb: 35000,
        overage_speed_mbps: new Decimal('0.5'),
        voice_minutes: 350,
        sms_included: 35,
        network_type: 'LTE',
        subscription_services: [],
        badges: [],
      },
      {
        id: 21,
        name: '5G 프로',
        price: 125000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('11.0'),
        voice_minutes: -1,
        sms_included: 550,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'TVING',
        ],
        badges: ['프로'],
      },
      {
        id: 22,
        name: 'LTE 컴팩트',
        price: 32000,
        data_amount_mb: 28000,
        overage_speed_mbps: new Decimal('0.4'),
        voice_minutes: 280,
        sms_included: 28,
        network_type: 'LTE',
        subscription_services: [],
        badges: ['경제'],
      },
      {
        id: 23,
        name: '5G 엔터프라이즈',
        price: 160000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('20.0'),
        voice_minutes: -1,
        sms_included: 1000,
        network_type: '5G',
        subscription_services: [
          'NETFLIX',
          'YOUTUBE_PREMIUM',
          'DISNEY+',
          'WAVVE',
          'TVING',
          'MILLIE',
        ],
        badges: ['최고급'],
      },
      {
        id: 24,
        name: 'LTE 프리미엄 플러스',
        price: 65000,
        data_amount_mb: 80000,
        overage_speed_mbps: new Decimal('2.0'),
        voice_minutes: 800,
        sms_included: 80,
        network_type: 'LTE',
        subscription_services: ['TVING', 'WAVVE'],
        badges: [],
      },
      {
        id: 25,
        name: '5G 스트리밍',
        price: 90000,
        data_amount_mb: 0,
        overage_speed_mbps: new Decimal('6.0'),
        voice_minutes: -1,
        sms_included: 300,
        network_type: '5G',
        subscription_services: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+'],
        badges: ['스트리밍'],
      },
      {
        id: 26,
        name: 'LTE 스탠다드 플러스',
        price: 58000,
        data_amount_mb: 65000,
        overage_speed_mbps: new Decimal('1.8'),
        voice_minutes: 650,
        sms_included: 65,
        network_type: 'LTE',
        subscription_services: ['TVING'],
        badges: [],
      },
      {
        id: 27,
        name: '5G 라이트',
        price: 60000,
        data_amount_mb: 50000,
        overage_speed_mbps: new Decimal('2.5'),
        voice_minutes: 500,
        sms_included: 50,
        network_type: '5G',
        subscription_services: ['YOUTUBE_PREMIUM'],
        badges: ['신규'],
      },
      {
        id: 28,
        name: 'LTE 이코노미 플러스',
        price: 40000,
        data_amount_mb: 38000,
        overage_speed_mbps: new Decimal('0.6'),
        voice_minutes: 380,
        sms_included: 38,
        network_type: 'LTE',
        subscription_services: [],
        badges: ['저렴'],
      },
    ],
    skipDuplicates: true,
  });

  // -----------------------------
  // Subscribes Seed
  // -----------------------------
  await prisma.subscribe.createMany({
    data: [
      {
        id: 1,
        name: '넷플릭스 프리미엄',
        price: 17000,
        monthly_price: 17000,
        category: 'OTT',
        benefits: ['4K 화질', '동시 시청 4명', '광고 없음'],
        description: '최고 화질의 영화와 드라마를 광고 없이 시청하세요',
        badges: ['인기', '추천'],
      },
      {
        id: 2,
        name: '유튜브 프리미엄',
        price: 13900,
        monthly_price: 13900,
        category: 'OTT',
        benefits: ['광고 없음', '백그라운드 재생', '오프라인 저장'],
        description: '유튜브를 광고 없이, 백그라운드에서도 즐기세요',
        badges: ['인기'],
      },
      {
        id: 3,
        name: '디즈니+',
        price: 9900,
        monthly_price: 9900,
        category: 'OTT',
        benefits: ['디즈니 콘텐츠', '4K 화질', '다운로드'],
        description: '디즈니, 마블, 스타워즈를 한 곳에서',
        badges: [],
      },
      {
        id: 4,
        name: '스포티파이',
        price: 10900,
        monthly_price: 10900,
        category: 'MUSIC',
        benefits: ['광고 없음', '오프라인 재생', '고음질'],
        description: '전 세계 음악을 광고 없이',
        badges: ['인기'],
      },
      {
        id: 5,
        name: '밀리의 서재',
        price: 9900,
        monthly_price: 9900,
        category: 'EDUCATION',
        benefits: ['무제한 독서', '오디오북', '이벤트'],
        description: '책 한 달에 10권 이상 읽는 사람들을 위한',
        badges: [],
      },
      {
        id: 6,
        name: '뉴스스탠드',
        price: 4900,
        monthly_price: 4900,
        category: 'NEWS',
        benefits: ['다양한 뉴스', '오프라인 읽기', '요약 기능'],
        description: '세상의 모든 뉴스를 한 곳에서',
        badges: [],
      },
      {
        id: 7,
        name: '쿠팡플레이',
        price: 4990,
        monthly_price: 4990,
        category: 'OTT',
        benefits: ['무제한 시청', '쿠팡 와우 혜택'],
        description: '쿠팡 와우 회원을 위한 스트리밍 서비스',
        badges: ['특가'],
      },
      {
        id: 8,
        name: '애플 뮤직',
        price: 11000,
        monthly_price: 11000,
        category: 'MUSIC',
        benefits: ['광고 없음', '공간 음향', '라이브 라디오'],
        description: 'Apple 기기와 완벽하게 연동되는 음악 서비스',
        badges: [],
      },
      {
        id: 9,
        name: '유튜브 프리미엄 + 추가혜택(택1)',
        price: 13900,
        monthly_price: 13900,
        category: 'OTT',
        benefits: ['유튜브 프리미엄', '추가 라이프 혜택'],
        description: '유튜브 프리미엄과 추가 라이프 혜택까지',
        badges: ['BEST'],
      },
      {
        id: 10,
        name: '더블 스트리밍 연간권',
        price: 226800,
        monthly_price: 18900,
        category: 'OTT',
        benefits: ['넷플릭스', '유튜브 프리미엄'],
        description: '넷플릭스+유튜브 프리미엄 국내 유일 월 18,900원!',
        badges: ['특가'],
      },
      {
        id: 11,
        name: '티빙 월정액 이용권',
        price: 4950,
        monthly_price: 4950,
        category: 'OTT',
        benefits: ['티빙 오리지널', '방송', '영화', '해외시리즈'],
        description: '티빙 오리지널 콘텐츠, 방송, 영화, 해외시리즈까지!',
        badges: ['할인'],
      },
      {
        id: 12,
        name: '유튜브 프리미엄 + 이모티콘플러스 구독팩',
        price: 14900,
        monthly_price: 14900,
        category: 'OTT',
        benefits: ['유튜브 프리미엄', '카카오 이모티콘 무제한'],
        description: '유튜브프리미엄과 카카오이모티콘 무제한 구독상품을 한번에',
        badges: [],
      },
      {
        id: 13,
        name: '넷플릭스 월정액',
        price: 7000,
        monthly_price: 7000,
        category: 'OTT',
        benefits: ['무제한 시청', '다양한 콘텐츠'],
        description: '넷플릭스에서 영화와 시리즈를 무제한으로 즐겨보세요!',
        badges: ['할인'],
      },
      {
        id: 14,
        name: '디즈니 + 추가혜택(택1)',
        price: 9900,
        monthly_price: 9900,
        category: 'OTT',
        benefits: ['디즈니+', '추가 라이프 혜택'],
        description: '디즈니+와 추가 라이프 혜택까지',
        badges: ['U⁺ 모바일 전용'],
      },
      {
        id: 15,
        name: '디즈니+월정액 이용권',
        price: 9405,
        monthly_price: 9405,
        category: 'OTT',
        benefits: ['스트리밍', '다양한 콘텐츠'],
        description: '지금 스트리밍중! 내가 좋아하는 이야기가 모두 여기에!',
        badges: ['할인'],
      },
      {
        id: 16,
        name: '유튜브 프리미엄 + 배달의민족 구독팩',
        price: 17900,
        monthly_price: 17900,
        category: 'OTT',
        benefits: ['유튜브 프리미엄', '배달의민족 5,000원 교환권'],
        description: '매월 제공되는 배달앱 1위 배민 5,000원 교환권 제공!',
        badges: [],
      },
      {
        id: 17,
        name: '지니뮤직 마음껏듣기 월정액',
        price: 7900,
        monthly_price: 7900,
        category: 'MUSIC',
        benefits: ['무제한 스트리밍', '데이터 무료'],
        description: '데이터 걱정없는 무제한 나만의 음악 요정 지니',
        badges: ['U⁺ 모바일 전용'],
      },
      {
        id: 18,
        name: '지니뮤직 + 추가혜택(택1)',
        price: 8400,
        monthly_price: 8400,
        category: 'MUSIC',
        benefits: ['지니뮤직', '추가 라이프 혜택'],
        description: '지니뮤직과 추가 라이프 혜택까지',
        badges: ['U⁺ 모바일 전용'],
      },
      {
        id: 19,
        name: '유튜브 프리미엄 + 스타벅스 구독팩',
        price: 17900,
        monthly_price: 17900,
        category: 'OTT',
        benefits: ['유튜브 프리미엄', '스타벅스 5,000원 모바일카드'],
        description:
          '유튜브프리미엄과 매월 제공되는 스타벅스 5,000원 모바일카드!',
        badges: [],
      },
      {
        id: 20,
        name: '유튜브 프리미엄 + CGV 구독팩',
        price: 15900,
        monthly_price: 15900,
        category: 'OTT',
        benefits: ['유튜브 프리미엄', 'CGV 영화 1+1'],
        description: '유튜브는 광고없이 프리미엄 영화는 1+1 스마트하게!',
        badges: ['U⁺ 모바일 전용'],
      },
    ],
    skipDuplicates: true,
  });

  console.log('✅ Seed 완료 (Plans + Subscribes)');
}

main()
  .catch((e) => {
    console.error('❌ Seed 실패:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
